site_name: Docs Portal Demo
docs_dir: docs

theme:
  name: material

# Navigation
nav:
  # - Home: index.md
  # - Frontend:
  #     - Overview: releases/v1.0.0/frontend/index.md
  # - Backend:
  #     - Overview: releases/v1.0.0/backend/index.md
  # - Infra:
  #     - Overview: releases/v1.0.0/infra/index.md
  - ホーム: index.md
  - 版本选择: versions.md
  - フロントエンド:
      - 概要: releases/v1.0.0/frontend/README.md
      - 全体構成: releases/v1.0.0/frontend/src/README.md
      - チャット管理: releases/v1.0.0/frontend/src/chat/README.md
      - 認証情報: releases/v1.0.0/frontend/src/auth/README.md
      - 画面一覧: releases/v1.0.0/frontend/src/pages/README.md
      - 共通レイアウト: releases/v1.0.0/frontend/src/layout/README.md
      - 共通フック: releases/v1.0.0/frontend/src/hooks/README.md

  - バックエンド:
      - 概要: releases/v1.0.0/backend/README.md
      - 全体構成: releases/v1.0.0/backend/app/README.md
      - REST API概要: releases/v1.0.0/backend/app/api/README.md
      - LLM連携: releases/v1.0.0/backend/app/integrations/README.md
      - DDBリポジトリ: releases/v1.0.0/backend/app/repositories/README.md
      - サービス: releases/v1.0.0/backend/app/services/README.md
      - タスク: releases/v1.0.0/backend/app/tasks/README.md

  - インフラ:     
      - 概要: releases/v1.0.0/infra/README.md 

copyright: Copyright © 2026 - 2040 - Classmethod, Inc.
